### ISSUE TITLE
XLS file not recognised 

### ISSUE THREAD

**Issue by neilharvey** [neilharvey/FileSignatures#12]
The [bug-xls-not-recognised](https://github.com/neilharvey/FileSignatures/tree/bug-xls-not-recognised) branch contains an example XLS file which is not being recognised.

Debugger shows the following values for the CFBF header:

    ByteOrder: 65534
    DifatSectorCount: 0
    DirectorySectorsCount: 0
    FatSectorsCount: 1
    FirstDifatSectorLocation: -2
    FirstDirectorySectorLocation: 12
    FirstMiniFatSectorLocation: -2
    HeaderCLSID: {byte[16]}
    HeaderSignature: {byte[8]}
    MajorVersion: 3
    MiniFatSectorCount: 0
    MiniSectorShift: 6
    MiniStreamCutoffSize: 4096
    MinorVersion: 62
    Reserved: {byte[6]}
    SectorShift: 9
    TransactionSignatureNumber: 0

Which returns zero for the object type field so the file is not recognised.

**Comment by neilharvey** [comment]
I've tried two different CFB file inspectors and in both cases the CLSID was detected as zero.

**Comment by mexvod** [comment]
Hi. I suggest not to use CLSID. I suggest reading the files also as we read open xml format. See merge request. The question remains how to watch msg.  https://en.wikipedia.org/wiki/COM_Structured_Storage  https://www.mitec.cz/ssv.html https://github.com/ironfede/openmcdf

**Comment by mexvod** [comment]
https://blogs.msdn.microsoft.com/openspecification/2009/11/06/msg-file-format-part-1/   ?????? __properties_version1.0

**Comment by neilharvey** [comment]
This has been fixed by https://github.com/neilharvey/FileSignatures/pull/13
