### ISSUE TITLE
Enable Sponsorships?

### ISSUE THREAD

**Issue by tiesont** [neilharvey/FileSignatures#20]
Not to tell you how to manage your project, but would you mind enabling the Sponsorships setting on your repo? Been playing around with this for a bit, and what you've built here is allowing me to clean up a few areas of my project which need to discover the actual MIME of a user-submitted file. I feel it's only fair to pay that back in some fashion, even if it's just to cover the cost of a few frosty adult beverages...

Regardless, you have my gratitude, my new friend!

**Comment by neilharvey** [comment]
Hey man, thanks for the offer but I did all the hard work on this a while back - most of the work nowadays is fixing the occasional issue.  Knowing that this small project is useful to someone is reward enough :)
