### ISSUE TITLE
OpenMCDF instead of OpeMCDF-2 ?

### ISSUE THREAD

**Issue by JiriZidek** [neilharvey/FileSignatures#21]
Have you considered changing dependency from 
https://github.com/CodeCavePro/OpenMCDF (OpenMCDF-2)
to
https://github.com/ironfede/openmcdf  (OpenMCDF)
that looks better maintained ?

**Comment by neilharvey** [comment]
Hey, I wasn't aware of OpenMCDF, the OpenMCDF-2 dependency came in via a PR.   

Comparing the code bases,  it looks as though OpenMCDF-2 was a fork of OpenMCFD which only has a single contributor so I think you're probably right, OpenMCDF will likely have better maintenance in the long-term.

**Comment by JiriZidek** [comment]
I just noticed these two met side-by-side in one of my project, so I studied how this had happened....

**Comment by neilharvey** [comment]
I did wonder what lead you to spot it :)

**Comment by neilharvey** [comment]
This has been changed in v4.0.

**Comment by mexvod** [comment]
Why did you change the library? Now you will be illegally processed compound storage formats.

**Comment by neilharvey** [comment]
@mexvod As discussed above, the dependency was changed because OpenMCDF-2 appeared to be a fork with fewer maintainers.  It appears that they have the same licence?

https://github.com/ironfede/openmcdf/blob/master/License.txt
https://github.com/CodeCavePro/OpenMCDF/blob/master/LICENSE.md

**Comment by mexvod** [comment]
Yes it is. But version 2 of the library had the correct file processing algorithm, unlike the original. I need to conduct additional tests to determine the correct operation.

**Comment by JiriZidek** [comment]
1 - in what sense do you mean "correct" ?
2 - maybe it is time to file an Issue at the original project and suggest a fix ?
