### ISSUE TITLE
TIFF signature is incorrect

### ISSUE THREAD

**Issue by neilharvey** [neilharvey/FileSignatures#29]
We are using `49 49 2A 00` as the signature for TIFF images but the first two bytes are actually the byte order mark.  `49 49` indicates little endian ("II" - Intel byte order) and `4D 4D` indicates big endian ("MM" - Motorola byte order).

**Comment by cocowalla** [comment]
I believe this is only half the fix tho? The TIFF format still always looks for `0x2a, 0x00` at offset 2 - but it'll be `0x00, 0x2a` for big endian TIFFs.
