### ISSUE TITLE
Mime-Detective Major Update Available

### ISSUE THREAD

**Issue by TonyValenti** [neilharvey/FileSignatures#36]
Hi @neilharvey -
I wanted to let you know that a major update to Mime-Detective has been released:
https://github.com/MediatedCommunications/Mime-Detective
https://www.nuget.org/packages/Mime-Detective/

I wanted to personally let you know because concepts in it are based on the great work you did with FileSignatures.  Because of that, I also listed you as an author on the newest release.

If you have any future ideas, I also wanted to personally invite you to consider contributing future work toward Mime-Detective as well.

I hope to see you around!

**Comment by neilharvey** [comment]
Thanks, glad to see you've published the library  - apologies for my previous doubts.  

Good luck with the release of your library and all the best.
