### ISSUE TITLE
Possible to update your release to the latest version of OpenMcdf, please?

### ISSUE THREAD

**Issue by arachnodedotnet** [neilharvey/FileSignatures#37]
Possible to update your release to the latest version of OpenMcdf, please?

**Comment by neilharvey** [comment]
@arachnodedotnet Done!  I'll push a new release in a bit (once I've put my kid to bed :)

**Comment by neilharvey** [comment]
Hey, I've published a release and pushed the new package to NuGet.  May take an hour or so before it appears as live.
