### ISSUE TITLE
Signed assembly (strong-named)

### ISSUE THREAD

**Issue by gigi81** [neilharvey/FileSignatures#38]
Hi,
We would like to use FileSignatures in a project that is strongly named (signed).

From the docs:
A strong-named assembly can only use types from other strong-named assemblies. Otherwise, the integrity of the strong-named assembly would be compromised.
https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named

Would it be possible to sign the assembly that is in the nuget package. I'm happy to have a PR for this, just wondering if it is something that would be open to. All dotnet libraries usually comes strongly named (signed) including the dotnet core ones.

**Comment by neilharvey** [comment]
Hey, yep I'm happy to do that - if you send a PR I'll republish a new package.

**Comment by gigi81** [comment]
fantastic @neilharvey I will try and do that today then. thanks!

**Comment by neilharvey** [comment]
Thanks for the PR - I've published the new version as 4.1 - https://www.nuget.org/packages/FileSignatures/4.1.0.  Gimme a shout if any issues.

**Comment by gigi81** [comment]
Tested and it works fine. Thank you very much for such a fast turnaround!
Closing as fixed.
