### ISSUE TITLE
Some PDF are not recognized

### ISSUE THREAD

**Issue by MaximeLaffaire** [neilharvey/FileSignatures#66]
Hi 🙂 

There is a problem in the pdf format recognition: the code is looking for the 4 bytes header `%PDF` at the very beginning of a file, but in some cases a pdf file can have data before this header, as described in this [documentation ](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.3.pdf) page 644 under "File Header".

Also, the header can be in the format `%!PS−Adobe−N.n PDF−M.m`.

I can send a PR with this changes, what do you think ? 

Thanks :)

**Comment by neilharvey** [comment]
Ah, that's interesting!  Sure, feel free to submit a PR if you have something in mind :)

If you have a sample PDF that demonstrates the issue it would be really useful, I usually pop a case in the [FunctionalTests.cs](https://github.com/neilharvey/FileSignatures/blob/master/test/FileSignatures.Tests/FunctionalTests.cs).  If you don't have a suitable sample, no worries - I trust the spec.

**Comment by MaximeLaffaire** [comment]
Hi @neilharvey 

Out of curiosity, do you know when you'll be able to publish a new version of the package including theses changes please :) ? 

Thank you :)

**Comment by neilharvey** [comment]
Hey, sorry meant to push it over the weekend but it slipped my mind :)  

I've pushed the package to NuGet, it should show up shortly.  Thanks again for the contribution!

**Comment by MaximeLaffaire** [comment]
Hi again @neilharvey 

I think you might have pushed the wrong version, seems like the last changes are not included 🥲 
I don't see the changes when I decompile the .dll and seems like [the version bundled in the nuget package is the 4.4.1](https://nuget.info/packages/FileSignatures/5.0.0)

**Comment by neilharvey** [comment]
Huh, that's weird.  This is what I get for skipping a prerelease package ;)

Looking through my logs I can see what's happened - whilst a build was run prior to packing, the configuration wasn't set so it defaulted to Debug, whereas the pack defaulted to Release so it pulled the old version. I'll sort it and republish a new version.

**Comment by neilharvey** [comment]
New version has been published, it should be available shortly.  I'll leave the issue open until we've confirmed it's OK.

**Comment by MaximeLaffaire** [comment]
Looks like it's all good now :D 
Thank you for your time :)
